import "./globals.css";
import Layout from "@/components/Layout";   // ✅ Default import

export const metadata = {
  title: "Inventory Management System",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
